# The Basics

In [2]:
import numpy as np

print(np.__version__)

1.21.1


In [43]:
a = np.array([1, 3, 6, 9], dtype='int16')
print(a)

[1 3 6 9]


In [44]:
b = np.array([[3.0,9.0,5.0], [1.,79.0,4.9]])
print(b)

[[ 3.   9.   5. ]
 [ 1.  79.   4.9]]


In [6]:
#Get Dimension
a.ndim

1

In [7]:
#Get Shape
b.shape

(2, 3)

In [15]:
a.shape

(4,)

In [13]:
#Get Type
a.dtype

dtype('int16')

In [17]:
b.dtype

dtype('float64')

In [45]:
#Get Size
a.size

4

In [46]:
b.size

6

In [20]:
#Get Total Size
a.nbytes

8

In [22]:
b.nbytes

48

# Accessing/Changing specific elements, rows, columns, etc.

## 2-D Array

In [70]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
#Get a specific element [r, c]
a[1,5] 
#or a[1,-2]

13

In [28]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#Get a specific column
a[:, 4]

array([ 5, 12])

In [34]:
#Doing more specific elements [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [38]:
#Re-assigning values in the array
a[1,5] = 20
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [39]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [40]:
a[:,2] = [3, 10]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [9]:
#Get elements divisible by 2
a[a%2==0]

array([2, 4, 6])

In [11]:
#Get element 5 and up
print((a>5) | (a==5))

[False False False False  True  True]


## 3-D Array

In [50]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
#Get specific element  (work outside in)
b[0,1,:]

array([3, 4])

In [53]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [55]:
b[:,1,1]

array([4, 8])

In [56]:
b[0,:,1]

array([2, 4])

In [57]:
#Replacing elements in the array
b[:,1,:] = [[78,34], [22,56]]
print(b)

[[[ 1  2]
  [78 34]]

 [[ 5  6]
  [22 56]]]


### How to add a new axis to an array

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [6]:
a2 = a[np.newaxis, :] #row_vector
a2.shape

(1, 6)

In [8]:
a3 = a[:, np.newaxis] #col_vector
a3.shape

(6, 1)

## Initialize Different Types of Arrays

In [58]:
#All 0s matrix
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [64]:
np.zeros((3,6,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
#All 1s matrix
np.ones((4, 5, 3), dtype = 'int16')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [69]:
#Any other number
np.full((3,5), 77)

array([[77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [73]:
#Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [75]:
#Random decimal numbers
np.random.rand(4,2,3)

array([[[0.52377068, 0.5487126 , 0.62447777],
        [0.75361022, 0.63481249, 0.41067721]],

       [[0.43877076, 0.99803905, 0.33267422],
        [0.90917438, 0.05982844, 0.29511519]],

       [[0.24277012, 0.78659221, 0.1740675 ],
        [0.31484721, 0.6654373 , 0.08847503]],

       [[0.64149175, 0.05211724, 0.65573071],
        [0.50221994, 0.18744121, 0.01911279]]])

In [86]:
np.random.random_sample(a.shape)

array([[0.23252098, 0.46116439, 0.27726669, 0.5987351 , 0.17023959,
        0.22901113, 0.5696084 ],
       [0.99991291, 0.16844318, 0.73811295, 0.00275439, 0.15681662,
        0.65347567, 0.24129701]])

In [84]:
#Random integer values
np.random.randint(-4, 9, size=(3,3))

array([[ 1, -4, -4],
       [ 2,  7,  3],
       [-4,  1,  5]])

In [35]:
#generating a matrix with random integers between 0 & 4
rng = np.random.default_rng(0)
rng.integers(5, size=(2, 4))

array([[4, 3, 2, 1],
       [1, 0, 0, 0]], dtype=int64)

In [88]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
#repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
#get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
uni = np.unique(a)
print(uni)

[11 12 13 14 15 16 17 18 19 20]


In [40]:
#Get the indices of unique values
uni, ind = np.unique(a ,return_index=True)
print(ind)

[ 0  2  3  4  5  6  7 12 13 14]


In [41]:
#Get the count of unique values
uni, count = np.unique(a, return_counts=True)
print(count)

[3 2 2 2 1 1 1 1 1 1]


In [45]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
uni = np.unique(a_2d, axis=0) #row
print(uni)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
uni = np.unique(a_2d, axis=1) #col
print(uni)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [100]:
#Creating a complex matrix
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


- **Be careful while copying arrays.**

In [111]:
a = np.array([1,2,3])
b = a.copy() #do NOT forget to add copy(), otherwise changes you run in b will also happen in a.
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Basic Mathematics in NumPy

In [121]:
a = np.array((1,2,3,4))
print(a)

[1 2 3 4]


In [122]:
a + 2

array([3, 4, 5, 6])

In [115]:
a - 2

array([-1,  0,  1,  2])

In [116]:
a * 2

array([2, 4, 6, 8])

In [117]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [123]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [124]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [131]:
#Take sin of an array
np.sin(a)

#cos and tan values of a 
#np.cos(a)
#np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

## Linear Algebra

In [134]:
#Matrix Multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [136]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [21]:
stats = np. array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
                   [0.54627315, 0.05093587, 0.40067661, 0.55645993],
                   [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
stats

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [22]:
np.min(stats)

0.05093587

In [27]:
np.min(stats, axis = 0) # givevs the  minimum value within each column

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [28]:
np.min(stats, axis = 1) # givevs the  minimum value within each row

array([0.17296777, 0.05093587, 0.12697628])

In [24]:
np.max(stats)

0.82485143

In [25]:
np.sum(stats)

4.8595784

In [30]:
#Doing Arithematic Operations on matices of diif. sizes
d = np.array([[1, 2], [3, 4], [5, 6]])
one_row = np.array([[1,1]])

d + one_row #NumPy uses its broadcast rules for this operation.

array([[2, 3],
       [4, 5],
       [6, 7]])

## Reeorginizing Arrays

In [48]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [49]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [50]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
#Use transpose() to reverse the axes of an array
before.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [59]:
#flipping 1-D arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
rev= np.flip(arr)
print('Reversed array: ', rev)

Reversed array:  [8 7 6 5 4 3 2 1]


In [60]:
#flipping 2-D arrays
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
rev_2d = np.flip(arr_2d)
print(rev_2d)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [62]:
#reversing rows
rev_row = np.flip(arr_2d, axis = 0)
print(rev_row)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [64]:
#reversing columns
rev_col = np.flip(arr_2d, axis=1)
print(rev_col)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [65]:
#flipping only second row
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [66]:
#fliping second column
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [152]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

np.vstack([v1,v2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [153]:
np.vstack([v1,v2, v2, v1])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [154]:
#Horizantally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [155]:
np.hstack([h2,h1])

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [14]:
#Splitting long arrays into small arrays
x = np.arange(1,25).reshape(2,12)
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [15]:
np.hsplit(x,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [17]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

## Miscellaneous

### Load data from file

In [162]:
data = np.genfromtxt('data.txt', delimiter = ',')
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

### Changing data type of a file

In [164]:
data = data.astype('int32')
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking & Advanced Indexing

In [160]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [165]:
data[data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [169]:
np.any(data > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [170]:
np.all(data > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [172]:
((data > 50) & (data < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [173]:
(~(data > 50) & (data < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [178]:
prob = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])
prob

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [179]:
prob[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [185]:
prob[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [186]:
prob[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])